print('-'*39)
print('|',' '*8,'Roberto',' '*22,'|',sep='')
print('|',' '*37,'|',sep='')
print('|',' '*8,'5786',' '*25,'|',sep='')
print('|',' '*37,'|',sep='')
print('|',' '*8,'UNIFEI',' '*23,'|',sep='')
print('-'*39)
